<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Subhadip" failures="3" tests="5" name="MasterTest" time="35.659" errors="0" timestamp="2024-12-23T14:21:31 IST">
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="11.622">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC004_LoginDataDrivenTest.validate_login(TC004_LoginDataDrivenTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="2.246">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC004_LoginDataDrivenTest.validate_login(TC004_LoginDataDrivenTest.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="2.215">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC004_LoginDataDrivenTest.validate_login(TC004_LoginDataDrivenTest.java:78)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="11.675"/>
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="1.992"/>
</testsuite> <!-- MasterTest -->
